//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by iocli

package sms

import (
	"github.com/alibaba/ioc-golang/autowire"
	"github.com/alibaba/ioc-golang/autowire/singleton"
	"github.com/photowey/helloioc/internal/message"
)

func init() {
	singleton.RegisterStructDescriptor(&autowire.StructDescriptor{
		Interface: new(message.Message),
		Factory: func() interface{} {
			return &Sender{}
		},
	})
}
