//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by iocli

package order

import (
	"github.com/alibaba/ioc-golang/autowire"
	"github.com/alibaba/ioc-golang/autowire/singleton"
)

func init() {
	singleton.RegisterStructDescriptor(&autowire.StructDescriptor{
		Alias:     "order",
		Interface: &Order{},
		Factory: func() interface{} {
			return &Order{}
		},
	})
}
