//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by iocli

package redis

import (
	"github.com/alibaba/ioc-golang/autowire"
	"github.com/alibaba/ioc-golang/autowire/singleton"
)

func init() {
	singleton.RegisterStructDescriptor(&autowire.StructDescriptor{
		Alias: "RedisAlias",
		Factory: func() interface{} {
			return &Redis{}
		},
		ParamFactory: func() interface{} {
			var _ paramInterface = &Param{}
			return &Param{}
		},
		ConstructFunc: func(i interface{}, p interface{}) (interface{}, error) {
			param := p.(paramInterface)
			impl := i.(*Redis)
			return param.Init(impl)
		},
	})
}

type paramInterface interface {
	Init(impl *Redis) (*Redis, error)
}
